# ---------------------------------------------------------------------------
# Generate the tiny synthetic fixture committed to inst/extdata/sim/.
#
# Run from the package root:   Rscript data-raw/make_fixture.R
# Requires on PATH: badread, art_illumina, gzip (development-only tools,
# not dependencies of the installed package).
#
# Output is fully deterministic: one set.seed() drives genome and variants,
# and Badread/ART receive fixed seeds. Regenerating on the same tool versions
# reproduces the committed files byte for byte (gzip -n, no timestamps).
# ---------------------------------------------------------------------------

source(file.path("data-raw", "simulate_genome.R"))

out_dir <- file.path("inst", "extdata", "sim")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
path <- function(...) file.path(out_dir, ...)

set.seed(20261009)

contig     <- "chr1"
genome_len <- 200000L
gc_content <- 0.42
ont_depth_per_hap <- 15   # 2 haplotypes -> ~30x total
ill_depth_per_hap <- 15   # 2 haplotypes -> ~30x total

message("Simulating reference (", genome_len, " bp, GC ", gc_content, ") ...")
ref <- sim_reference(genome_len, gc_content)

message("Planting variants ...")
vars <- sim_variants(ref, chrom = contig,
                     n_snv = 250, n_indel = 40, max_indel = 30,
                     n_del = 3, n_ins = 3, n_dup = 2, n_inv = 2,
                     sv_len_range = c(300, 1500))

message("Building haplotypes ...")
hap1 <- build_haplotype(ref, vars, hap = 1)
hap2 <- build_haplotype(ref, vars, hap = 2)

message("Writing FASTA / VCF / GFF3 truth files ...")
write_fasta(setNames(list(as.character(ref)), contig), path("genome.fa"))
write_fasta(setNames(list(hap1), paste0(contig, "_hap1")), path("hap1.fa"))
write_fasta(setNames(list(hap2), paste0(contig, "_hap2")), path("hap2.fa"))
write_truth_vcf(vars, contig, genome_len, path("truth_small.vcf"), sv = FALSE)
write_truth_vcf(vars, contig, genome_len, path("truth_sv.vcf"), sv = TRUE)
write_gff3(contig, genome_len, path("genes.gff3"))

message("Simulating Nanopore reads with Badread ...")
simulate_nanopore(c(path("hap1.fa"), path("hap2.fa")),
                  path("ont_reads.fastq.gz"),
                  depth = ont_depth_per_hap, seed = 101)

message("Simulating Illumina reads with ART ...")
simulate_illumina(c(path("hap1.fa"), path("hap2.fa")),
                  path("ill_R1.fastq.gz"), path("ill_R2.fastq.gz"),
                  depth = ill_depth_per_hap, seed = 202)

message("Writing sample sheet ...")
write.csv(data.frame(
  sample          = "sim1",
  reads           = "ont_reads.fastq.gz",
  illumina_r1     = "ill_R1.fastq.gz",
  illumina_r2     = "ill_R2.fastq.gz",
  truth_small_vcf = "truth_small.vcf",
  truth_sv_vcf    = "truth_sv.vcf"
), path("sample_sheet.csv"), row.names = FALSE, quote = FALSE)

# --- summary / sanity checks ------------------------------------------------

n_fastq_reads <- function(fq_gz) {
  con <- gzfile(fq_gz, "r")
  on.exit(close(con))
  n <- 0L
  while (length(chunk <- readLines(con, 40000)) > 0) n <- n + length(chunk)
  n %/% 4L
}
total_bases <- function(fq_gz) {
  con <- gzfile(fq_gz, "r")
  on.exit(close(con))
  bases <- 0
  repeat {
    chunk <- readLines(con, 40000)
    if (length(chunk) == 0) break
    idx <- seq(2, length(chunk), by = 4)
    bases <- bases + sum(nchar(chunk[idx]))
  }
  bases
}

ont_bases <- total_bases(path("ont_reads.fastq.gz"))
ill_reads <- n_fastq_reads(path("ill_R1.fastq.gz"))
tool_ver <- function(cmd, args) {
  out <- tryCatch(suppressWarnings(
    system2(cmd, args, stdout = TRUE, stderr = TRUE)),
    error = function(e) "unavailable")
  paste(head(out[nzchar(out)], 3), collapse = " ")
}

summary_lines <- c(
  "# Synthetic fixture (inst/extdata/sim)",
  "",
  "Generated by `data-raw/make_fixture.R` (seeded, deterministic).",
  "Regenerate from the package root with: `Rscript data-raw/make_fixture.R`",
  "",
  sprintf("- reference: %s, %d bp, GC %.2f, 2 dispersed repeat copies + 1 tandem array",
          contig, genome_len, gc_content),
  sprintf("- variants: %d SNVs, %d small indels, %d SVs (%s)",
          sum(vars$class == "small" & nchar(vars$ref) == 1 & nchar(vars$alt) == 1),
          sum(vars$class == "small" & (nchar(vars$ref) > 1 | nchar(vars$alt) > 1)),
          sum(vars$class == "sv"),
          paste(names(table(vars$svtype)), table(vars$svtype),
                sep = "=", collapse = ", ")),
  sprintf("- Nanopore reads: Badread, %dx per haplotype (~%.0fx total), %.1f Mb",
          ont_depth_per_hap, ont_bases / genome_len, ont_bases / 1e6),
  sprintf("- Illumina reads: ART HS25, 2x150 bp, %dx per haplotype, %d pairs",
          ill_depth_per_hap, ill_reads),
  "",
  "## Files",
  "",
  "| file | description |",
  "|---|---|",
  "| genome.fa | reference contig |",
  "| hap1.fa / hap2.fa | the two haplotype sequences the reads were simulated from |",
  "| truth_small.vcf | phased truth SNVs + indels (<50 bp) |",
  "| truth_sv.vcf | phased truth SVs (DEL/INS/DUP/INV, sequence-resolved) |",
  "| genes.gff3 | minimal gene models for custom SnpEff databases |",
  "| ont_reads.fastq.gz | simulated Nanopore reads |",
  "| ill_R1.fastq.gz / ill_R2.fastq.gz | simulated paired-end Illumina reads |",
  "| sample_sheet.csv | ready-to-use sample sheet (paths relative to this dir) |",
  "",
  "## Tool versions at generation time",
  "",
  sprintf("- badread: %s", tool_ver("badread", "--version")),
  sprintf("- art_illumina: %s",
          sub(".*(Version [0-9.]+).*", "\\1",
              paste(tool_ver("art_illumina", "-h"), collapse = " ")))
)
writeLines(summary_lines, path("README.md"))

message("Done. Fixture written to ", normalizePath(out_dir))
message(sprintf("  ONT: %.1f Mb (~%.0fx), Illumina pairs: %d (~%.0fx)",
                ont_bases / 1e6, ont_bases / genome_len, ill_reads,
                ill_reads * 2 * 150 / genome_len))
